version: '3.8'

services:

  nginx:
    build: ./nginx
    volumes:
      - static_data:/usr/src/app/staticfiles/
    ports:
      - 80:80
    depends_on:
      - app

  app:
    build: ./app
    command: gunicorn seqsleuth.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - genome_data:/usr/data/
      - static_data:/usr/src/app/staticfiles/
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis

  search-worker:
    build: ./app
    command: celery --app seqsleuth worker -l info
    env_file:
      - ./.env.prod
    volumes:
      - genome_data:/usr/data/
    depends_on:
      - db
      - redis

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  redis:
    image: redis:7-alpine

volumes:
  postgres_data:
  genome_data:
  static_data:
