# Generated by Django 3.2.5 on 2022-05-12 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('S', 'Submitted'), ('R', 'Running'), ('C', 'Complete'), ('E', 'Error')], default='S', max_length=1, verbose_name='job status')),
                ('started', models.DateTimeField(auto_now_add=True, verbose_name='time search was submitted')),
                ('finished', models.DateTimeField(null=True, verbose_name='time search was finished')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genome', models.CharField(max_length=10)),
                ('protein', models.CharField(max_length=10)),
                ('start', models.IntegerField(default=-1)),
                ('end', models.IntegerField(default=-1)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searches.search')),
            ],
        ),
    ]
